services:
  api:
    restart: always
    depends_on:
      db:
        condition: service_healthy
    build:
      context: ./api
    secrets:
      - db-password
    environment:
      - POSTGRES_DB=jobs
      - POSTGRES_USER=jobs-web
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
    volumes:
      - uploads:/uploads
    expose:
      - 8080
    networks:
      - backend-net

  db:
    image: postgres:16-alpine
    restart: always
    user: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    secrets:
      - db-password
    environment:
      - POSTGRES_DB=jobs
      - POSTGRES_USER=jobs-web
      - POSTGRES_PASSWORD_FILE=/run/secrets/db-password
    expose:
      - 5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U jobs-web -d jobs"]
      interval: 3s
      timeout: 1s
      retries: 5
    networks:
      - backend-net

  frontend:
    build:
      context: .
      args:
        VITE_API_BASE_URL: /api
    ports:
      - "8088:8080"
    depends_on:
      - api
    security_opt:
      - no-new-privileges:true
    networks:
      - backend-net

networks:
  backend-net:
    driver: bridge

volumes:
  db-data:
  uploads:


secrets:
  db-password:
    file: db/password.txt
