services:
  api:
    restart: always
    depends_on:
      db:
        condition: service_healthy
    build:
      context: ./api
    secrets:
      - db-password
    environment:
      - POSTGRES_DB=jobs
      - POSTGRES_USER=jobs-web
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
    ports:
      - 8080:8080
  db:
    image: postgres
    restart: always
    user: postgres
    secrets:
      - db-password
    volumes:
      - db-data:/var/lib/postgresql
    environment:
      - POSTGRES_DB=jobs
      - POSTGRES_USER=jobs-web
      - POSTGRES_PASSWORD_FILE=/run/secrets/db-password
    expose:
      - 5432
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "jobs-web", "-d", "jobs" ]
      interval: 3s
      timeout: 1s
      retries: 5

volumes:
  db-data:

secrets:
  db-password:
    file: db/password.txt
